CC = gcc
CFLAGS = -W -Wall -pedantic -std=gnu99 -g

EXECUTABLES = factorial forkdemo execdemo matrix twoscomp

all: $(EXECUTABLES)

factorial: factorial.c

forkdemo: forkdemo.c

execdemo: execdemo.c

matrix: matrix.c

twoscomp: twoscomp.c

clean:
	rm -f $(EXECUTABLES)
